import { getMe } from "@/api/auth";
import AppInitializer from "@/components/layout/app-initializer";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: {
  children: Readonly<React.ReactNode>;
}) {
  const { me } = await getMe();
  return <AppInitializer user={me}>{children}</AppInitializer>;
}
