import type { Metadata } from "next";
import LocaleLayout from "@/components/layout/locale-dashboard";
import { Providers } from "../providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <LocaleLayout>{children}</LocaleLayout>
    </Providers>
  );
}
